### ISSUE TITLE
Enable users to save searches as required in RF10

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/ckanext-dalrrd-emc-dcpr#257] opened 2022-07-26 09:59 UTC
RF10 - Create saved searches. Registered users shall be able to save search parameters in order to be able to reproduce a search query at a future date.

I was not able to save search parameters also inhibiting my ability to test RF11 and RF12.

**Comment by gubuntu** [comment] 2022-07-27 11:41
duplicate of #137

**Closed by gubuntu** 2022-07-27 11:41 UTC
