### ISSUE TITLE
Add templates for customization of DCPR-related activities

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#179] opened 2022-05-24 20:56 UTC
Don't forget to show a link to the actual DCPR request in those activities that are relevant

**Comment by gubuntu** [comment] 2022-07-28 09:13
Please clarify this and link to a requirement and client UI/UX confirmation before coding

**Comment by gubuntu** [comment] 2022-09-05 11:36
linked to or duplicate of 276?

**Comment by Samweli** [comment] 2022-09-13 11:04
Not sure about this, it doesn't seem to be linked to the #276

**Comment by gubuntu** [comment] 2022-10-05 15:45
@Samweli please find out from @ricardogsilva else move to the bottom of the backlog else close

**Comment by Samweli** [comment] 2022-10-05 15:55
> @Samweli please find out from @ricardogsilva else move to the bottom of the backlog else close

Right, @gubuntu.

**Closed** 2023-05-23 06:10 UTC
